---
- name: ec2 launcher
  hosts: localhost
  connection: local
  vars:
      instance_type: t2.micro
      security_group: hilla_AWS_Security_Grp
      image: ami-00bb6f60
      keypair: hillagold
      region: us-west-2
      count: 1

  tasks:
    - name: Setting up Security/Firewall Group
      ec2_group:
         name: '{{ security_group }}'
         description: Rules Allowing Traffic on port 22
         region: '{{ region }}'
         rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_iip: 0.0.0.0/0
         rules_egress:
           - porto: all
             cidr_ip: 0.0.0.0/0

    - name: launching ec2
      ec2:
        instance_type: '{{ instance_type }}'
        key_name: '{{ keypair }}'
        image: '{{ image }}'
        region: '{{ region }}'
        group: deafult
        count: '{{ count }'
        vpc_subnet_id: subnet-bd8434e0
        wait: yes
        assign_public_ip: yes
        group: hilla_AWS_Security_Grp
      register: ec2_out
    - debug:
         msg: ansible_default_ipv4.gateway {{ ansible_default_ipv4.gateway }}
         when: ansible_default_ipv4.gateway is defined

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} pot=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2_out.instances }}'
