---
- name: ec2 launcher
  hosts: localhost

  tasks:
    - name: launching ec2
      ec2:

        instance_type: t2.micro
        key_name: hillagold
        image: ami-00bb6f60
        region: us-west-2
        group: deafult
        count: 1
        vpc_subnet_id: subnet-bd8434e0
        wait: yes
        assign_public_ip: yes
               
