---
- name: ec2 launcher
  hosts: localhost
  connection: local

  tasks:
    - name: Setting up Security/Firewall Group
      ec2_group:
         name: hilla_AWS_Security_Grp
         description: Rules Allowing Traffic on port 22
         region: us-west-2
         rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_iip: 0.0.0.0/0
          rules_egress:
           - porto: all
             cidr_ip: 0.0.0.0/0

    - name: launching ec2
      ec2:
        instance_type: t2.micro
        key_name: hillagold
        image: ami-00bb6f60
        region: us-west-2
        group: deafult
        count: 1
        vpc_subnet_id: subnet-bd8434e0
        wait: yes
        assign_public_ip: yes
        group: hilla_AWS_Security_Grp
      register: ec2_out
    - debug:
         msg: ansible_default_ipv4.gateway {{ ansible_default_ipv4.gateway }}
         when: ansible_default_ipv4.gateway is defined

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} pot=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2_out.instances }}'


    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
