---
- name: ec2 launcher
  hosts: localhost
  connection: local
  vars:
      instance_type: t2.micro
      security_group: hilla_AWS_Security_Grp
      image: ami-00bb6f60
      keypair: hillagold
      region: us-west-2
      count: 1

  tasks:
    - name: launching ec2
      ec2:
        instance_type: '{{ instance_type }}'
        key_name: '{{ keypair }}'
        image: '{{ image }}'
        region: '{{ region }}'
        count: '{{ count }'
        vpc_subnet_id: subnet-bd8434e0
        wait: yes
        assign_public_ip: yes
        group: default
      register: ec2_out
    - debug:
         msg: ansible_default_ipv4.gateway {{ ansible_default_ipv4.gateway }}
         when: ansible_default_ipv4.gateway is defined

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} pot=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2_out.instances }}'
