---
- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: False  
  vars:
      instance_type: c1.medium
      image: ami-1336d57a
      keypair: hillagold
      region: us-west-2
      count: 1
      vpc_subnet_id: subnet-bd8434e0

  tasks:
    - name: launching ec2
      become: yes
      ec2:
        instance_type: '{{ instance_type }}'
        key_name: '{{ keypair }}'
        aws_access_key: "AKIA52PY7VUJWXAUGY7A"
        aws_secret_key: "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"
        image: '{{ image }}'
        region: '{{ region }}'
        count: '{{ count }}'
        vpc_subnet_id: '{{vpc_subnet_id }}'
        wait: yes
        assign_public_ip: yes
        group: default
      register: ec2_out

    - name: curl
      shell: curl -L "https://dl.bintray.com/hillagold/conan-repo/Hello/0.1@cyber/beta" -o hello

    - name: terminate
      ec2:
        instance_ids: '{{item.instance_id}}'
        region: '{{ region }}'
        state: absent
        wait: yes
      with_items: '{{ec2_out.instances}}'

