---
- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: False  
  vars:
      instance_type: t2.micro
      image: ami-898dd9b9
      keypair: hillagold
      region: us-west-2
      count: 1
      vpc_subnet_id: subnet-bd8434e0
      conan_package: Hello/0.1@cyber/beta
      conan_name: conan-repo

  tasks:
    - name: launching ec2
      become: yes
      ec2:
        instance_type: '{{ instance_type }}'
        key_name: '{{ keypair }}'
        aws_access_key: "AWS_SECRET_ACCESS_KEY"
        aws_secret_key: "AWS_SECRET_KEY"
        image: '{{ image }}'
        region: '{{ region }}'
        count: '{{ count }}'
        vpc_subnet_id: '{{vpc_subnet_id }}'
        wait: yes
        assign_public_ip: yes
        group: default
      register: ec2_out

    - name: make sure pip is present
      command: pip --version
      register: cn
      ignore_errors: yes

    - name: pip non present, install
      package:
        name: python-pip
      become: yes
      when: cn["failed"]

    - name: upgrade pip
      command: pip install --upgrade pip
      become: yes

    - name: install conan
      pip:
        name: conan
        state: latest
      become: yes

    - name: add repositories
      command: "conan remote add {{ item.name }} {{ item.uri }} "
      with_items:
        - { name: "{{ conan_name }}", uri: "https://api.bintray.com/conan/hillagold/conan-repo" }
      ignore_errors: yes

    - name: Create a directory if it does not exist
      file:
        path: build
        state: directory
        mode: '0755'

    - name: partition new disk
      shell: /bin/echo -e "n\np\n1\n\n\nw" | sudo fdisk /dev/mapper/ubuntu--vg-root

    - name: download Hello package
      command: "conan install .. {{ conan_package }} -r {{ conan_name }} > hello"

    - name: terminate
      ec2:
        instance_ids: '{{item.instance_id}}'
        region: '{{ region }}'
        state: absent
        wait: yes
      with_items: '{{ec2_out.instances}}'
